<a href="https://colab.research.google.com/github/raisaurabh44/Census-income-project/blob/main/Census_Income.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Census Income Project

In [1]:
# importing the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
df= pd.read_csv('/content/drive/MyDrive/CSGO_Project Census-Income/census-income .csv')

In [3]:
df

age         workclass  fnlwgt   education  education-num  \
0       39         State-gov   77516   Bachelors             13   
1       50  Self-emp-not-inc   83311   Bachelors             13   
2       38           Private  215646     HS-grad              9   
3       53           Private  234721        11th              7   
4       28           Private  338409   Bachelors             13   
...    ...               ...     ...         ...            ...   
32556   27           Private  257302  Assoc-acdm             12   
32557   40           Private  154374     HS-grad              9   
32558   58           Private  151910     HS-grad              9   
32559   22           Private  201490     HS-grad              9   
32560   52      Self-emp-inc  287927     HS-grad              9   

           marital-status         occupation   relationship   race     sex  \
0           Never-married       Adm-clerical  Not-in-family  White    Male   
1      Married-civ-spouse    Exec-managerial        Husband  White    Male   
2                Divorced  Handlers-cleaners  Not-in-family  White    Male   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4      Married-civ-spouse     Prof-specialty           Wife  Black  Female   
...                   ...                ...            ...    ...     ...   
32556  Married-civ-spouse       Tech-support           Wife  White  Female   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White    Male   
32558             Widowed       Adm-clerical      Unmarried  White  Female   
32559       Never-married       Adm-clerical      Own-child  White    Male   
32560  Married-civ-spouse    Exec-managerial           Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country annual_income  
0              2174             0              40  United-States         <=50K  
1                 0             0              13  United-States         <=50K  
2                 0             0              40  United-States         <=50K  
3                 0             0              40  United-States         <=50K  
4                 0             0              40           Cuba         <=50K  
...             ...           ...             ...            ...           ...  
32556             0             0              38  United-States         <=50K  
32557             0             0              40  United-States          >50K  
32558             0             0              40  United-States         <=50K  
32559             0             0              20  United-States         <=50K  
32560         15024             0              40  United-States          >50K  

[32561 rows x 15 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64 
 5   marital-status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64 
 11  capital-loss    32561 non-null  int64 
 12  hours-per-week  32561 non-null  int64 
 13  native-country  32561 non-null  object
 14  annual_income   32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [5]:
df.shape

(32561, 15)

In [6]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
annual_income     0
dtype: int64

In [14]:
df.duplicated().sum()

0

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

0

In [26]:
df['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [27]:
df=df.replace('?',np.nan)

In [28]:
df.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     582
annual_income        0
dtype: int64

In [31]:
df=df.dropna()
df.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
annual_income     0
dtype: int64

In [33]:
num_col = df.select_dtypes(include=['float64', 'int64']).columns
cat_col = df.select_dtypes(include=['object']).columns

In [34]:
cat_col

Index(['workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country', 'annual_income'],
      dtype='object')

In [43]:
df.describe().T

count           mean            std      min       25%  \
age             30139.0      38.441720      13.131426     17.0      28.0   
fnlwgt          30139.0  189795.025980  105658.624341  13769.0  117627.5   
education-num   30139.0      10.122532       2.548738      1.0       9.0   
capital-gain    30139.0    1092.841202    7409.110596      0.0       0.0   
capital-loss    30139.0      88.439928     404.445239      0.0       0.0   
hours-per-week  30139.0      40.934703      11.978753      1.0      40.0   

                     50%       75%        max  
age                 37.0      47.0       90.0  
fnlwgt          178417.0  237604.5  1484705.0  
education-num       10.0      13.0       16.0  
capital-gain         0.0       0.0    99999.0  
capital-loss         0.0       0.0     4356.0  
hours-per-week      40.0      45.0       99.0

In [44]:
df.describe(include='O').T

count unique                 top   freq
workclass       30139      7             Private  22264
education       30139     16             HS-grad   9834
marital-status  30139      7  Married-civ-spouse  14059
occupation      30139     14      Prof-specialty   4034
relationship    30139      6             Husband  12457
race            30139      5               White  25912
sex             30139      2                Male  20366
native-country  30139     41       United-States  27487
annual_income   30139      2               <=50K  22633

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('unique').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [51]:
df[num_col].nunique()

age                  72
fnlwgt            20263
education-num        16
capital-gain        118
capital-loss         90
hours-per-week       94
dtype: int64

In [52]:
df[cat_col].nunique()

workclass          7
education         16
marital-status     7
occupation        14
relationship       6
race               5
sex                2
native-country    41
annual_income      2
dtype: int64

In [53]:
# Label Encodings
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for col in df.columns:
  if df[col].dtype=='object':
    df[col]=le.fit_transform(df[col])

In [54]:
df.head()

age  workclass  fnlwgt  education  education-num  marital-status  \
0   39          5   77516          9             13               4   
1   50          4   83311          9             13               2   
2   38          2  215646         11              9               0   
3   53          2  234721          1              7               2   
4   28          2  338409          9             13               2   

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           0             1     4    1          2174             0   
1           3             0     4    1             0             0   
2           5             1     4    1             0             0   
3           5             0     2    1             0             0   
4           9             5     2    0             0             0   

   hours-per-week  native-country  annual_income  
0              40              38              0  
1              13              38              0  
2              40              38              0  
3              40              38              0  
4              40               4              0

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30139 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             30139 non-null  int64
 1   workclass       30139 non-null  int64
 2   fnlwgt          30139 non-null  int64
 3   education       30139 non-null  int64
 4   education-num   30139 non-null  int64
 5   marital-status  30139 non-null  int64
 6   occupation      30139 non-null  int64
 7   relationship    30139 non-null  int64
 8   race            30139 non-null  int64
 9   sex             30139 non-null  int64
 10  capital-gain    30139 non-null  int64
 11  capital-loss    30139 non-null  int64
 12  hours-per-week  30139 non-null  int64
 13  native-country  30139 non-null  int64
 14  annual_income   30139 non-null  int64
dtypes: int64(15)
memory usage: 3.7 MB


In [64]:
# seperate Independent and dependent
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

print(x.shape)
print(y.shape)

(30139, 14)
(30139,)


In [65]:
from sklearn.model_selection import train_test_split

x_train, x_test , y_train , y_test = train_test_split(x,y, test_size=0.3, random_state=42)

In [66]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(21097, 14)
(9042, 14)
(21097,)
(9042,)


In [69]:
# scaling we do
from sklearn.preprocessing import StandardScaler

sc= StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [70]:
x_train

array([[ 0.0367706 , -0.21041787, -0.07250973, ..., -0.21844668,
        -0.49726516,  0.26384612],
       [-0.34230943, -0.21041787,  0.76576125, ..., -0.21844668,
         0.75686551,  0.26384612],
       [ 0.64329865, -0.21041787,  1.03468981, ..., -0.21844668,
        -0.0792216 ,  0.26384612],
       ...,
       [-0.11486141, -0.21041787, -0.12066877, ..., -0.21844668,
         4.85369239,  0.26384612],
       [ 0.79493066, -0.21041787, -0.6194295 , ..., -0.21844668,
        -0.0792216 ,  0.26384612],
       [-0.94883747, -0.21041787,  1.60996257, ..., -0.21844668,
        -0.0792216 ,  0.26384612]])

In [71]:
x_test

array([[-0.56975745, -0.21041787,  0.19550206, ..., -0.21844668,
        -0.0792216 ,  0.26384612],
       [-0.41812543, -0.21041787, -0.26539418, ..., -0.21844668,
         0.33882196,  0.26384612],
       [-1.2521015 , -0.21041787,  1.8007652 , ..., -0.21844668,
        -0.0792216 ,  0.26384612],
       ...,
       [-0.87302147,  0.83779603,  0.42198229, ..., -0.21844668,
        -0.24643903,  0.26384612],
       [ 0.56748264, -0.21041787,  0.25667731, ..., -0.21844668,
        -0.0792216 ,  0.26384612],
       [ 0.71911465, -2.30684568, -0.90907131, ..., -0.21844668,
         0.33882196,  0.26384612]])

In [73]:
#Moddle building
from sklearn.linear_model import LogisticRegression

md1=LogisticRegression()
md1.fit(x_train,y_train)

LogisticRegression()

In [74]:
y_pred=md1.predict(x_test)

In [75]:
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [76]:
from sklearn.metrics import *

In [78]:
accuracy_score(y_test,y_pred)*100

82.19420482194205

In [79]:
confusion_matrix(y_test,y_pred)

array([[6383,  366],
       [1244, 1049]])

In [80]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6749
           1       0.74      0.46      0.57      2293

    accuracy                           0.82      9042
   macro avg       0.79      0.70      0.73      9042
weighted avg       0.81      0.82      0.81      9042



In [82]:
!pip install pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.9/485.9 kB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 48.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.5/160.5 kB 13.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 257.7/257.7 kB 22.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 12.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.1/81.1 kB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.9/21.9 MB 56.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 72.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 71.9 MB/s 

In [1]:
import pandas as pd
from pycaret.classification import *
#from pycaret.regression import *
# Load your dataset
data=pd.read_csv('/content/drive/MyDrive/CSGO_Project Census-Income/census-income .csv')

In [2]:
clf_setup = setup(data, target='annual_income')


In [3]:
best_model = compare_models()

Processing:   0%|          | 0/65 [00:00<?, ?it/s]